version: '3.8'

services:
  # Redis Cluster (3主3从)
  redis-node1:
    image: redis:7.0
    container_name: redis-node1
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7001
    ports:
      - "7001:7001"
      - "17001:17001"
    # volumes:
    #   - redis-data1:/data
    networks:
      - cluster-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7001", "ping"]
      interval: 5s

  redis-node2:
    image: redis:7.0
    container_name: redis-node2
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7002
    ports:
      - "7002:7002"
      - "17002:17002"
    # volumes:
    #   - redis-data2:/data
    networks:
      - cluster-net

  redis-node3:
    image: redis:7.0
    container_name: redis-node3
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7003
    ports:
      - "7003:7003"
      - "17003:17003"
    # volumes:
    #   - redis-data3:/data
    networks:
      - cluster-net

  # ETCD Cluster (3节点)
  etcd1:
    image: bitnami/etcd:latest
    container_name: etcd1
    environment:
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"
    # volumes:
    #   - etcd-data1:/etcd-data
    networks:
      - cluster-net

  etcd2:
    image: bitnami/etcd:latest
    container_name: etcd2
    environment:
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2479:2379"
      - "2480:2380"
    # volumes:
    #   - etcd-data2:/etcd-data
    networks:
      - cluster-net

  etcd3:
    image: bitnami/etcd:latest
    container_name: etcd3
    environment:
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2579:2379"
      - "2580:2380"
    # volumes:
    #   - etcd-data3:/etcd-data
    networks:
      - cluster-net

# volumes:
#   redis-data1:
#   redis-data2:
#   redis-data3:
#   etcd-data1:
#   etcd-data2:
#   etcd-data3:

networks:
  cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16